name: Example Workflow

on:
  push:  # Trigger on push
    branches:
      - main
      - develop
  pull_request:  # Trigger on pull request
    branches:
      - main
  workflow_dispatch:  # Manual trigger
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "staging"
  schedule:  # Scheduled trigger
    - cron: "0 5 * * *"  # Every day at 5:00 AM

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a shell command
        run: echo "Workflow triggered!"